name: 'Government URLs'
description: 'An API for searching against all the government URLs - all of them. '
license: null
openSourceProject: 1
governmentWideReuseProject: 0
tags:
    - GSA
    - DigitalGovSearch
    - domains
    - websites
contact:
    email: search@support.digitalgov.gov
