bundler_args: --without development production
language: ruby
rvm:
  - 2.2.2
before_install:
  - wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb && sudo dpkg -i --force-confnew elasticsearch-1.2.1.deb && true
  - sudo service elasticsearch start